### ISSUE TITLE
Citizens2插件无法添加NPC

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#101]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304.jar

### Java 版本 | 操作系统

系统：Windows 11  Java：zulu18.32.13-ca-jdk18.0.2.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
Citizens-2.0.32-b3174.jar
ProtocolLib.jar
```

### 错误描述

开启代理再次运行服务器后，可以正常进入服务器，但是启动后会报错，且/npc2 create awa生成npc后会直接报错游戏崩服

### 复现步骤

开启代理再次运行服务器后，可以正常进入服务器，但是启动后会报错，且/npc2 create awa生成npc后会直接报错游戏崩服

### 报错信息

[latest.log](https://github.com/MohistMC/Banner/files/12214338/latest.log)
[crash-2023-07-31_19.04.30-server.txt](https://github.com/MohistMC/Banner/files/12214339/crash-2023-07-31_19.04.30-server.txt)
最新请见下方评论

**Comment by 5ur3z** [comment]
[plugins.zip](https://github.com/MohistMC/Banner/files/12214342/plugins.zip)

**Comment by 5ur3z** [comment]
开启代理再次运行服务器后，可以正常进入服务器，但是启动后会报错，且/npc2 create awa生成npc后会直接报错游戏崩服
[crash-2023-07-31_19.27.11-server.txt](https://github.com/MohistMC/Banner/files/12214519/crash-2023-07-31_19.27.11-server.txt)
[latest.log](https://github.com/MohistMC/Banner/files/12214520/latest.log)

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/077207a5-145a-4a1c-9c13-f67675bea2ed)
Check your network
