### ISSUE TITLE
服务器端装入末地乐事、起源模组后无法启动

### ISSUE THREAD

**Issue by wumengzhixing** [MohistMC/Banner#104]
### 请确认您已完成以下几件事

- [ ] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-304

### Java 版本 | 操作系统

java version "19.0.1" 2022-10-18

### 相关 Mod/插件 的名称及版本

```raw
banner-1.20.1-304.jar
fabric-api-0.86.1+1.20.1.jar
Origins-1.20.1-1.10.0
farmers-delight-fabric-mc1.20.1-1.4.1
ends_delight-fabric-1.20.1-1.0
```

### 错误描述

起源模组：https://www.mcmod.cn/class/3111.html
农夫乐事：https://www.mcmod.cn/class/2820.html

服务器端装入其中一个模组后就无法启动

### 复现步骤

安装起源/农夫乐事模组

### 报错信息

[farmers-delight的日志.log](https://github.com/MohistMC/Banner/files/12216711/farmers-delight.log)
[Origins-1.20.1-1.10.0的日志.log](https://github.com/MohistMC/Banner/files/12216713/Origins-1.20.1-1.10.0.log)

**Comment by 5ur3z** [comment]
确认单独安装农夫乐事可以正常启动

**Comment by wumengzhixing** [comment]
> 确认单独安装农夫乐事可以正常启动

诶，我的问题，我只看到了农夫乐事的错误。那应该是和末地乐事有问题
https://www.mcmod.cn/class/6298.html

**Comment by wumengzhixing** [comment]
> apoli是哪个模组？

额，我也不清楚。我这边并没有装这个模组

**Comment by suiheng** [comment]
> apoli是哪个模组？

![image](https://github.com/MohistMC/Banner/assets/81475218/0c5e7f67-bf22-450b-9424-46825f304522)
参考PCL的搜索（

**Comment by wdog5** [comment]
https://github.com/apace100/apoli/blob/1.20/src/main/java/io/github/apace100/apoli/mixin/LivingEntityMixin.java

**Comment by Mgazul** [comment]
Fixed
