### ISSUE TITLE
生物碰到火焰后没有做出反应/火焰对生物伤害低

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#106]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

322

### Java 版本 | 操作系统

ZuluJDK18

### 相关 Mod/插件 的名称及版本

```raw
无
```

### 错误描述

如题

### 复现步骤

放几只猪，一个打火石，猪在火焰上血量消耗慢且不会做出奔跑动作

**Comment by DreamSoulFire** [comment]
切玩家被附魔火矢的箭射中也不会被火焰灼烧 只会受到箭矢伤害
