### ISSUE TITLE
模组不兼容

### ISSUE THREAD

**Issue by monsters-97** [MohistMC/Banner#125]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-368

### Java 版本 | 操作系统

openjdk version "20.0.1" 2023-04-18 OpenJDK Runtime Environment (build 20.0.1+10) OpenJDK 64-Bit Server VM (build 20.0.1+10, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
banner-1.20.1-368
carpet-fixes-1.20-1.16.1
PluslsCarpetAddition-1.20.1-0.3.176+56ccc7d-beta
```

### 错误描述

经过我的多次测试，banner与carpet fixes和pca均不兼容，在确定加载了最新模组以及前置的情况下，在存在banner时，只要加入carpet fixes或者pca，服务器将加载失败。
似乎跟mixin冲突有关

### 复现步骤

1、安装前置模组
fabric-api-0.86.1+1.20.1
magiclib-1.20.1-0.7.364+85d9866-stable
fabric-carpet-1.20-1.4.112+v230608
2、安装banner-1.20.1-368
3、安装carpet-fixes-1.20-1.16.1或者PluslsCarpetAddition-1.20.1-0.3.176+56ccc7d-beta
4、打开服务器，服务器在Loading libraries, please wait...后报错

### 报错信息

1、安装banner和pca时的日志
[latest.log](https://github.com/MohistMC/Banner/files/12304418/latest.log)
2、安装banner和carpet fixes时的日志
[latest.log](https://github.com/MohistMC/Banner/files/12304434/latest.log)

**Comment by KirisameMarisaMO** [comment]
这个好像是pca本身的问题

**Comment by monsters-97** [comment]
> 这个好像是pca本身的问题

如果是因为pca的问题，那carpet fixes又怎么解释嘞

**Comment by 3290736814** [comment]
作者速速出来

**Comment by wdog5** [comment]
carpet fixes重新了一些方法，连servercore也是不兼容的

**Comment by monsters-97** [comment]
well, I'll try to ask the authors of cf about the issue, so can you explain the pca issue, and is it also the case that the authors of pca are needed to solve the incompatibility issue?
