### ISSUE TITLE
Create mod incompatibility

### ISSUE THREAD

**Issue by whereareiam** [MohistMC/Banner#134]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner-1.20.1-389.jar

### OS & Java versions

Windows 11 | openjdk version "17.0.8" 2023-07-18 LTS

### Plugins and Mods

```raw
Plugins (2): LuckPerms, PlaceholderAPI

Mods: Banner, Create, Fabric API
```

### Description

The Create mod for 1.20.1 is under development, but it works correctly without Banner, but with it the server refuses to start.

Dev version: https://github.com/Fabricators-of-Create/Create/suites/15025969682/artifacts/857973646

### Step to reproduce

1. Install Create
2. Start server

### Logs

https://pastebin.com/vDe9XGj7

**Comment by windy664** [comment]
大佬你这个怎么跑的，为何我客户端上装Create, Fabric API居然跑不起来？？？是因为fabric版本太低了么

**Comment by windy664** [comment]
@Mgazul 能不能别closed啊，还是跑不起来。。

**Comment by windy664** [comment]
我测试完了 纯fabric官服能跑，但是banner不能跑
