### ISSUE TITLE
关于插件与权限问题

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#138]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

392

### Java 版本 | 操作系统

openjdk version "17.0.7" 2023-04-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
luckperm 杜蕾斯菜单
```

### 错误描述

最近，我遇到了一个小小的阻碍，即杜蕾斯菜单插件的权限问题。
您知道的，权限对于一个游戏社区的健康和稳定发展至关重要。它不仅仅是一串代码或一个功能标识，更是玩家在这个世界中的身份和地位的体现。当一个玩家获得某个权限，那意味着他获得了一种信任，一种认可。而当他被错误地告知没有权限时，这不仅仅是一个技术问题，更是对他信任的伤害。
我们尽了一切努力来解决这个问题。我们尝试了使用papi变量，希望能够从另一个角度获取权限信息，但仍然失败了。我们查看了所有的日志和报告，但并未发现任何异常。每当玩家告诉我们他们遇到了“没有权限”的提示，我们都深感失落和无奈。
我理解，banner和插件都有可能出现问题，这是技术发展的必然过程。但我写这issue，是希望您能感受到我和玩家的焦虑和期待。我真心希望得到您的帮助，找到这个问题的原因，并一起寻找解决方案。

**Comment by EXiaoYue** [comment]
发现了相同问题，luckperms的权限设置无法正确生效且无报错信息。但这个问题并不仅仅发生在luckperms这一个权限插件上面，Authme，Nexauth，Residence、GroupManager等与权限的知名插件在该服务端上均有类似问题，如Authme等登录插件的unlogingroup无法正确生效。

**Comment by windy664** [comment]
> 发现了相同问题，luckperms的权限设置无法正确生效且无报错信息。但这个问题并不仅仅发生在luckperms这一个权限插件上面，Authme，Nexauth，Residence、GroupManager等与权限的知名插件在该服务端上均有类似问题，如Authme等登录插件的unlogingroup无法正确生效。

最新构建已修复
