### ISSUE TITLE
末影珍珠崩服

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#149]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

418

### Java 版本 | 操作系统

openjdk version "17.0.7" 2023-04-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
banner
```

### 错误描述

使用末影珍珠崩服

### 报错信息

[crash-2023-08-19_21.29.50-server.txt](https://github.com/MohistMC/Banner/files/12385952/crash-2023-08-19_21.29.50-server.txt)

**Comment by Mgazul** [comment]
无法复现

**Comment by windy664** [comment]
> 无法复现

是往边界扔去 在mohist群反馈过了 好像前几天的事 给刷下去了

**Comment by Mgazul** [comment]
使用最新构建再测试一下
