### ISSUE TITLE
cmi执行命令，游戏内和控制台均报错

### ISSUE THREAD

**Issue by Despaitre876** [MohistMC/Banner#152]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner-1.20.1-420

### OS & Java versions

Win11 openjdk version "17.0.7" 2023-04-18 LTS

### Plugins and Mods

```raw
mods:adventure-platform-fabric, Banner Mod, MixinExtras, mixin-tools, i18n, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, mapping-io, adventure-api, adventure-key, adventure-platform-api, adventure-text-logger-slf4j, adventure-text-minimessage, adventure-text-serializer-ansi, adventure-text-serializer-gson, adventure-text-serializer-json, adventure-text-serializer-plain, examination-api, examination-string, terminalconsoleappender, log4j-iostreams, jline-terminal, jline-terminal-jansi, snakeyaml
plugins:CoreProtect, AuthMe, CMILib, SkinsRestorer, spark, eBackup, CMI
```

### Description

在banner核心中加入cmi，使用指令游戏内和控制台均会报错
![image](https://github.com/MohistMC/Banner/assets/136472967/5ed2666a-1f04-466c-97f7-34f87980078e)

### Logs

[latest.log](https://github.com/MohistMC/Banner/files/12407585/latest.log)

**Comment by Mgazul** [comment]
should be fixed
