### ISSUE TITLE
末影珍珠崩服

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#162]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

433

### Java 版本 | 操作系统

openjdk version "17.0.7" 2023-04-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
banner
```

### 错误描述

[crash-2023-09-03_04.37.26-server.txt](https://github.com/MohistMC/Banner/files/12504901/crash-2023-09-03_04.37.26-server.txt)

**Comment by windy664** [comment]
[crash-2023-10-03_20.16.19-server.txt](https://github.com/MohistMC/Banner/files/12792312/crash-2023-10-03_20.16.19-server.txt)
使用463还是有这个情况发生

**Comment by Mgazul** [comment]
已经470+了 你怎么还在测试463
