### ISSUE TITLE
CC: Tewaked 模组，和网络有关的兼容性问题

### ISSUE THREAD

**Issue by qyl27** [MohistMC/Banner#173]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-448

### Java 版本 | 操作系统

Win11；Temurin-17.0.6+10

### 相关 Mod/插件 的名称及版本

```raw
Fabric模组：
CC: Tweaked（1.20.1-fabric-1.108.1）
Fabric API（0.89.0+1.20.1）
```

### 错误描述

安装 CC Tweaked 模组之后无法进入服务器。
```
Internal Exception: io.netty.handler.codec.DecoderException: 
java.lang.IndexOutOfBoundsException: 
readerIndex(24847) + length(1) exceeds writerIndex(24847): 
UnpooledHeapByteBuf(ridx: 24847, widx: 24847, cap: 24847/24847)
```

### 复现步骤

1. 双端安装 Fabric API（0.89.0+1.20.1）、CC: Tweaked（1.20.1-fabric-1.108.1）；
2. 服务端安装 Banner（1.20.1-448）；
3. 尝试进入服务器。

**Comment by ERroooooR** [comment]
无法复现

**Comment by qyl27** [comment]
> 无法复现

那就先关掉吧，这个 issue 也有日子了。
