### ISSUE TITLE
[1.20.1] 原版矿车刷物品

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#175]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

463

### Java 版本 | 操作系统

openjdk version "17.0.7" 2023-04-18 LTS

### 相关 Mod/插件 的名称及版本

```raw
Banner
```

### 错误描述

![Uploading Screenshot_2023-10-01-11-31-38-269_com.tencent.mobileqq.jpg…]()

**Comment by windy664** [comment]
![Screenshot_2023-10-01-11-31-38-269_com tencent mobileqq](https://github.com/MohistMC/Banner/assets/81475218/b052dfe6-abac-4027-946a-edc18910f582)

**Comment by Mgazul** [comment]
无法复现

**Comment by windy664** [comment]
> 无法复现

自然矿洞里
