### ISSUE TITLE
[1.20.1] AssertionError Occurs Due to Unknown Entity Class 'BaseHamsterEntity' in amethyst imbuement Mod

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#180]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

473

### OS & Java versions

openjdk version 19

### Plugins and Mods

```raw
amethyst imbuement
```

### Description

While playing on a Minecraft server with the amethyst_imbuement mod installed, I encountered an AssertionError related to an unknown entity class BaseHamsterEntity. This error seems to occur when the server tries to handle this specific entity, but it fails as it doesn't recognize the entity class. I suspect this might be due to an issue with the mod installation, compatibility, or entity registration.

Error Message:
`java.lang.AssertionError: Unknown entity class me.fzzyhmstrs.amethyst_imbuement.entity.living.BaseHamsterEntity`

### Step to reproduce

1.Set Up the Server:

Set up a Minecraft server using Bukkit version v1_20_R1.
Ensure that Java version 19.0.2 is installed and used.
2.Install the Mod:

Install the amethyst_imbuement mod (mention the specific version of the mod if available).
3.Start the Server and Join the Game:

Start the Minecraft server and join the game.
4.Use the Item Related to the Mod:

Use an item related to the amethyst_imbuement mod that triggers the summoning of the BaseHamsterEntity. In the crash report, it is indicated that the error occurs during the use of an item, specifically when the use method is invoked in AugmentMiningItem.kt.
5.Observe the Crash:

The server should crash, and the error log should indicate an AssertionError pointing to the unknown BaseHamsterEntity class.

### Logs

[Uploading crash-2023-10-05_10.22.55-server.txt…]()

**Comment by windy664** [comment]
Oh 
Failed to upload successfully
I'ma upload it again
[crash-2023-10-05_10.22.55-server.txt](https://github.com/MohistMC/Banner/files/12813024/crash-2023-10-05_10.22.55-server.txt)

​

**Comment by Mgazul** [comment]
Fixed
