### ISSUE TITLE
自动选择下载源问题：根据系统语言和地区，而不是尝试获取当前IP判断

### ISSUE THREAD

**Issue by fr1g** [MohistMC/Banner#183]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-473

### Java 版本 | 操作系统

Zulu 17.44.53 | Windows Server 2022

### 相关 Mod/插件 的名称及版本

```raw
仅与本体相关。这更像是个建议。
```

### 错误描述

由于issue模板不存在Suggestion模板，所以只能以错误的形式提交。
Banner在首次运行时候会根据系统的语言和地区确认下载服务器，但我的服务器恰好在美国而且恰好在用中文的环境、地区也设置为中文、针对非unicode程序的语言选项也是中文。由此得到十分糟糕的资源补全（？）体验。希望借由IP测试API来判断地区。

### 复现步骤

 - 在美国准备全新的服务器环境，并且确保系统语言和地区等一律为中文（或中国）。
 - 启动服务端运行脚本

### 报错信息

这并非报错！它并没有不能用，只是这下载速度和主世界的岩浆一样。
---------
检查更新中...
如果不想启用更新检查，在banner-config/banner.yml中设置“check_update”为“false”
最新版本：473，当前版本：1.20.1-473。最新版本构建于2023-10-04 13:10:33，你应该升级到最新版本来修复最近的bug！
检查库文件中，请稍等...
下载源: CHINA
总进度 > 0%
……
---------

**Comment by Mgazul** [comment]
我记得配置文件可以自己设置下载源

**Comment by Mgazul** [comment]
banner.libraries_downloadsource: [CHINA|MOHIST|GITHUB] 三个可选源

**Comment by fr1g** [comment]
不然简单测个速来选择吧？Отправлено с iPhone6 окт. 2023 г., в 00:23, Mgazul ***@***.***> написал(а):﻿
找不到合适的识别接口, 用国内接口的话、国外访问不了，用国外接口的话、国内又访问不了

**Comment by Mgazul** [comment]
从你美国的服务器ping s1.devicloud.cn 看看延迟是多少

**Comment by fr1g** [comment]
平均252msОтправлено с iPhone7 окт. 2023 г., в 02:15, Mgazul ***@***.***> написал(а):﻿
从你美国的服务器ping s1.devicloud.cn 看看延迟是多少
