### ISSUE TITLE
Citizens Plugin Doesn't Work

### ISSUE THREAD

**Issue by creatorfromhell** [MohistMC/Banner#188]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner 1.20.1-475

### OS & Java versions

Windows 11, Java JDK 17

### Plugins and Mods

```raw
Mods:
- Fabric API
- Banner

Plugins:
- BetonQuest
- Citizens-2.0.32-b3208(latest for 1.20.1)
- ProtocolLib
```

### Description

Citizens plugin is incompatible with Banner. The issue seems to boil down to one line found here: https://github.com/CitizensDev/Citizens2/blob/master/v1_20_R2/src/main/java/net/citizensnpcs/nms/v1_20_R2/entity/EntityHumanNPC.java#L396 . When obfuscated it goes to this.bV in the EntityPlayer class.

### Step to reproduce

1. Install Citizens
2. use /npc create <name>
3. crash

After this point, if you simply startup the server you get a crash.

### Logs

[latest.log](https://github.com/MohistMC/Banner/files/12900682/latest.log)
[crash-2023-10-13_20.31.59-server.txt](https://github.com/MohistMC/Banner/files/12900685/crash-2023-10-13_20.31.59-server.txt)

### Server pack link (Optional)

n/a

**Comment by windy664** [comment]
Use citizens plugin , which has fixed in mohist qq group

**Comment by creatorfromhell** [comment]
> Use citizens plugin , which has fixed in mohist qq group

This is the citizens plugin...

**Comment by creatorfromhell** [comment]
Works as of latest banner version.
