### ISSUE TITLE
[1.20.1]banner不加载

### ISSUE THREAD

**Issue by lava191810** [MohistMC/Banner#191]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner未加载/1.20.1-493

### Java 版本 | 操作系统

系统：Android(PojavLanucher) JAVA：jre17-arm64-20230227-release

### 相关 Mod/插件 的名称及版本

```raw
fabric-api 0.90.4+1.20.1
fabricloader 0.14.24
java 17
minecraft 1.20.1
modmenu 7.2.2
banner 1.20.1/493
```

### 错误描述

我确保Banner位于mods文件夹中，但是fabricloader并不加载Banner

### 报错信息

[latest.log](https://github.com/MohistMC/Banner/files/13195075/latest.log)

**Comment by Mgazul** [comment]
Banner不支持客户端使用
