### ISSUE TITLE
[1.20.1] Porting_lib 不兼容

### ISSUE THREAD

**Issue by windy664** [MohistMC/Banner#194]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

494

### Java 版本 | 操作系统

openjdk version 19

### 相关 Mod/插件 的名称及版本

```raw
banner-1.20.1-494.jar
create-fabric-0.5.1-d-build.52+mc1.20.1.jar(https://github.com/DM-Earth/create-fabric-dme-edition/releases/tag/0.5.1-d-build.52%2Bmc1.20.1)
[前置]fabric-api-0.90.0+1.20.1.jar
[前置]fabric-language-kotlin-1.10.10+kotlin.1.9.10.jar
```

## Minecraft崩溃报告分析

- **时间**：2023-11-25 13:24:12
- **描述**：世界更新时异常

### 主要异常
- **类型**：`java.lang.RuntimeException`
- **信息**：`net.minecraft.world.level.NaturalSpawner`的Mixin转换失败

### 原因分析
- **Mixin转换错误**：这与Mixin转换过程中的失败有关。Mixin在Minecraft模组中用于修改或扩展游戏功能，而不更改原始源代码。
- **根本原因**：`org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError` - 这种错误通常是由不同模组之间或模组与游戏版本之间的冲突或不兼容引起的。

### 详细原因
- **注入错误**：`org.spongepowered.asm.mixin.injection.throwables.InjectionError`表明Mixin转换中的注入过程存在问题。这表明`net.minecraft.world.level.NaturalSpawner`中某个方法的局部变量表（LVT）存在不匹配。

### 涉及模组
- **Porting Lib Entity**：问题似乎源于`porting_lib_entity`模组，特别是`porting_lib_entity.mixins.json`中的一个Mixin配置。

### 报错信息

https://pastebin.com/kfCYUAfg

https://pastebin.com/XVrmX1jS

**Comment by ERroooooR** [comment]
副本https://github.com/MohistMC/Banner/issues/216

**Comment by windy664** [comment]
#561 已兼容
