### ISSUE TITLE
染色皮革物品在玩家背包中自动失去染色NBT。Dyed leather items automatically lose their dyed NBT in the player's inventory.

### ISSUE THREAD

**Issue by langru** [MohistMC/Banner#196]
### 请确认您已完成以下几件事

- [x] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-495

### Java 版本 | 操作系统

JDK 17.0.4.1 Windows 11

### 相关 Mod/插件 的名称及版本

```raw
fabric-api-0.90.7+1.20.1
lithium-fabric-mc1.20.1-0.11.2
starlight-1.1.2+fabric.dbc156f
worldedit-mod-7.2.15
```

### 错误描述

染色皮革物品在玩家背包中自动失去染色NBT。在方块、非玩家实体容器中，皮革染色NBT均不会消失。将带有染色NBT标签的皮革物品从方块或非玩家实体容器放入玩家物品栏中，染色NBT立即消失。 此问题能在旧issue中找到，但 wdog5 closed this as completed in 0051ba2 on Aug 9。

Translator Translation:
Dyed leather items automatically lose their dyed NBT in the player's inventory.In blocks and non-player entity containers, leather-dyed NBT will not disappear.Placing a leather item tagged with a dyed NBT tag from a block or non-player entity container into the player's inventory will cause the dyed NBT to disappear instantly.This issue can be found in the old issue，but wdog5 closed this as completed in 0051ba2 on Aug 9。

### 复现步骤

我尝试在服务端上仅安装fabricAPI模组、banner插件，此问题依然出现。移除banner插件后，此问题不再复现。

Translator Translation:
I tried to install only fabricAPI mod and banner plugins on the server side, and this issue still appears. After removing the banner plugin, this issue no longer reproduces.

### 报错信息

皮革染色NBT丢失时，服务端侧命令提示符无警告、无报错信息。

Translator Translation:
When the leather dyeing NBT is lost, there is no warning or error information in the command prompt on the server side.

**Comment by Dreamtell** [comment]
我也遇到同样的问题

**Comment by Dreamtell** [comment]
I'm having the same issue
