### ISSUE TITLE
paper/spigot版本的floodgate无法正常加载

### ISSUE THREAD

**Issue by liangcha385-1** [MohistMC/Banner#201]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-507

### Java 版本 | 操作系统

Java(TM) SE Runtime Environment (build 21.0.1+12-LTS-29) | Windows Server 2016

### 相关 Mod/插件 的名称及版本

```raw
plugins
floodgate-spigot（Build #85）
Geyser-Spigot(Bulid #389）
mods
fabric-api-0.91.0+1.20.1
banner-1.20.1-507
```

### 错误描述

添加floodgate后插件本体报错并自行卸载

geyser可以使基岩版用户加入Java版服务器
floodgate则可以允许经过 Xbox Live 身份验证的基岩客户端安全地加入您的联机服务器，而无需 Java 版帐户

### 复现步骤

1.安装fabric-server-mc.1.20.1-loader.0.15.1-launcher.0.11.2核心并启动服务器下载库文件
2.安装fabric-api-0.91.0+1.20.1和banner-1.20.1-507模组并启动服务器下载库文件
3.安装floodgate-spigot（Build #85）Geyser-Spigot(Bulid #389）插件并启动服务器
4.输出Done后输入/plugins若floodgate变红则复现成功

### 报错信息

[latest.log](https://github.com/MohistMC/Banner/files/13626555/latest.log)

**Comment by 0XPYEX0** [comment]
你说基岩版能装Fabric Mod吗？你这个想法就不切实际

**Comment by HaHaWTH** [comment]
Why don't use floodgate-fabric?🧐

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/2a96bd9e-3883-46a5-8bbd-f88a26dcca62)

**Comment by wdog5** [comment]
floodgate not support Banner,it is not recognise Banner as a platform
