### ISSUE TITLE
quilt crashes on 515 version

### ISSUE THREAD

**Issue by KirillkoTankisto** [MohistMC/Banner#205]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [ ] unable to reproduce in Spigot
- [ ] unable to reproduce in Fabric

### Banner version

1.20.1-515

### OS & Java versions

17.0.8.1

### Plugins and Mods

```raw
qfapi
```

### Description

just crashes when launch, even without any mods and plugins

### Step to reproduce

1. Launch server without any mods and plugins on quilt with qfapi

### Logs

https://pastebin.com/2a9BYe7g

**Comment by Mgazul** [comment]
Only supports fabric
