### ISSUE TITLE
Banner crashed without any mods & plugins

### ISSUE THREAD

**Issue by sj-hub9796** [MohistMC/Banner#209]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.20.1-520

### OS & Java versions

openjdk 17.0.9 2023-10-17

### Plugins and Mods

```raw
duplicate https://github.com/MohistMC/Banner/issues/208
```

### Description

duplicate https://github.com/MohistMC/Banner/issues/208

### Step to reproduce

duplicate https://github.com/MohistMC/Banner/issues/208

### Logs

https://mclo.gs/7rZv01E

**Comment by Mgazul** [comment]
This question has nothing to do with #208

**Comment by sj-hub9796** [comment]
> This question has nothing to do with #208

yeah you're right it's mybad
server crash even without those mod

**Comment by sj-hub9796** [comment]
I think problem is this commit: [link](https://github.com/MohistMC/Banner/commit/17e79cf2bdd5735ba5e8608930648198ad4fc33b)

**Comment by Mgazul** [comment]
Fixed
