### ISSUE TITLE
Why can't I put any plugin on my server?

### ISSUE THREAD

**Issue by nzmyOvO** [MohistMC/Banner#214]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.20.4-519

### OS & Java versions

build 17.0.9+11-LTS-201)

### Plugins and Mods

```raw
Mods : banner-1.20.4-519 - fabric-api-0.94.0+1.20.4
Plugins : It doesn't work
```

### Description

No plugin works for me and I get an error

### Step to reproduce

I installed everything I needed, checked it, but it won't load and I get an error about plugins

### Logs

EssentialsX - https://paste.ubuntu.com/p/PZ472mzsby/
WorldEdit - https://paste.ubuntu.com/p/H8d9wFwrnh/
SkinsRestorer - https://paste.ubuntu.com/p/TS3HP9rzDz/

**Comment by Mgazul** [comment]
1.20.4 has not been completed yet

**Comment by wdog5** [comment]
Fixed
