### ISSUE TITLE
Incompatibility with prominent 2 RPG modpack

### ISSUE THREAD

**Issue by ImKevinTbh** [MohistMC/Banner#230]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.20.1-565

### OS & Java versions

Windows Server 2022, openjdk 21.0.2 2024-01-16 LTS 

### Plugins and Mods

```raw
No plugins, prominence 2 modpack version 2.6.5
```

### Description

Server crashes on startup due to incompatibility with multiple mods, upon removing banner the server will boot fine

### Step to reproduce

Start server

Server crashes

### Logs

[latest.log](https://github.com/MohistMC/Banner/files/14212901/latest.log)

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg

**Comment by wdog5** [comment]
Fixed
