### ISSUE TITLE
Spawn underground

### ISSUE THREAD

**Issue by QuQuShKa1205** [MohistMC/Banner#238]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner-1.20.1-599

### OS & Java versions

Ubuntu 22.04 openjdk version "17.0.9"

### Plugins and Mods

```raw
mods: fabric api, banner

plugins: 0
```

### Description

Everything is in the video. There's nothing in the logs. https://www.youtube.com/watch?v=kVGppjN_pc0

### Step to reproduce

1. Start the server
2. Join
3. Thats all

### Logs

No logs

**Comment by Mgazul** [comment]
Fixed
