### ISSUE TITLE
不知道什么原因，打不开服务器，删上面说的3个应该有问题的模组也启动

### ISSUE THREAD

**Issue by CeydOuO** [MohistMC/Banner#261]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner-1.20.1-599-server.jar

### OS & Java versions

centos 9 jdk17

### Plugins and Mods

```raw
[19:03:19] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11

           |-- fabric-commands-v0 0.2.51+df3654b377
           |-- fabric-containers-v0 0.1.64+df3654b377
           |-- fabric-content-registries-v0 4.0.11+1802ada577
           |-- fabric-convention-tags-v1 1.5.5+1802ada577
           |-- fabric-crash-report-info-v1 0.2.19+1802ada577
           |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
           |-- fabric-data-generation-api-v1 12.3.4+1802ada577
           |-- fabric-dimensions-v1 2.1.54+1802ada577
           |-- fabric-entity-events-v1 1.6.0+1c78457f77
           |-- fabric-events-interaction-v0 0.6.2+1802ada577
           |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
           |-- fabric-game-rule-api-v1 1.0.40+1802ada577
           |-- fabric-item-api-v1 2.1.28+1802ada577
           |-- fabric-item-group-api-v1 4.0.12+1802ada577
           |-- fabric-key-binding-api-v1 1.0.37+1802ada577
           |-- fabric-keybindings-v0 0.2.35+df3654b377
           |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
           |-- fabric-loot-api-v2 1.2.1+1802ada577
           |-- fabric-loot-tables-v1 1.1.45+9e7660c677
           |-- fabric-message-api-v1 5.1.9+1802ada577
           |-- fabric-mining-level-api-v1 2.1.50+1802ada577
           |-- fabric-model-loading-api-v1 1.0.3+1802ada577
           |-- fabric-models-v0 0.4.2+9386d8a777
           |-- fabric-networking-api-v1 1.3.11+1802ada577
           |-- fabric-networking-v0 0.3.51+df3654b377
           |-- fabric-object-builder-api-v1 11.1.3+1802ada577
           |-- fabric-particles-v1 1.1.2+1802ada577
           |-- fabric-recipe-api-v1 1.0.21+1802ada577
           |-- fabric-registry-sync-v0 2.3.3+1802ada577
           |-- fabric-renderer-api-v1 3.2.1+1802ada577
           |-- fabric-renderer-indigo 1.5.2+85287f9f77
           |-- fabric-renderer-registries-v1 3.2.46+df3654b377

           |    |-- porting_lib_transfer 2.3.4+1.20.1
           |    |-- porting_lib_utility 2.3.4+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_client_events 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_config 2.3.4+1.20.1
           |    |-- com_electronwill_night-config_core 3.6.6
           |    |-- com_electronwill_night-config_toml 3.6.6
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_extensions 2.3.4+1.20.1
           |    |-- porting_lib_attributes 2.3.4+1.20.1
           |    |-- porting_lib_common 2.3.4+1.20.1
           |    |-- porting_lib_core 2.3.4+1.20.1
           |    \-- reach-entity-attributes 2.4.0
           |-- porting_lib_lazy_registration 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_loot 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_networking 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_recipe_book_categories 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_registries 2.3.4+1.20.1
           |    \-- porting_lib_core 2.3.4+1.20.1
           |-- porting_lib_tags 3.0
           |    \-- porting_lib_core 2.3.4+1.20.1
           \-- porting_lib_tool_actions 2.3.4+1.20.1
                \-- porting_lib_core 2.3.4+1.20.1
        - festive_delight 1.0.0
        - java 17
        - minecraft 1.20.1
        - pineapple_delight
```

### Description

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f98beca3421, pid=109129, tid=110255
#
# JRE version: OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition)-17.0.10.0.11+7-GA (17.0.10+7) (build 17.0.10+7)
# Java VM: OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition)-17.0.10.0.11+7-GA (17.0.10+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xaa3421]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x541
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/#BILICLUB/#BILICLUB-1/FABRIC/core.109129)
#
# An error report file with more information is saved as:
# /home/#BILICLUB/#BILICLUB-1/FABRIC/hs_err_pid109129.log
#
# If you would like to submit a bug report, please visit:
#   mailto:dragonwell_use@googlegroups.com
#
run.sh：行 9: 109129 已放弃               （核心已转储）java -Xms8192M -Xmx8192M -jar server.jar --nogui
Server restarting...
Press CTRL + C to stop.
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[19:00:20] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[19:00:20] [ForkJoinPool-1-worker-11/WARN]: Mod ends_delight uses the version refabricated-1.20.1-alpha-1.0 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'refabricated'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:00:20] [ForkJoinPool-1-worker-9/WARN]: Mod frightsdelight uses the version fabric-1.20.1-1.0.4 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[19:00:20] [ForkJoinPool-1-worker-7/WARN]: Mod oceansdelight uses the version fdrf-fabric-1.0.2-1.20 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fdrf'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**Comment by CeydOuO** [comment]
排查插件的时候，一个一个放进plugins排查的，都能暴毙。

**Comment by CeydOuO** [comment]
[hs_err_pid151522.log](https://github.com/user-attachments/files/15866251/hs_err_pid151522.log)

**Comment by CeydOuO** [comment]
windows系统可以开，但是centos9好像不行

**Comment by Mgazul** [comment]
建议用户你的系统开一个原版Fabric服试试

**Comment by CeydOuO** [comment]
![image](https://github.com/MohistMC/Banner/assets/37748919/db27cb8d-59a6-428b-860c-fda92d22feaa)
原版的开服没问题，但是装了banner然后随便装一个插件就会出现这个情况，但是自己电脑win11就没问题。banner-1.20.1-597-server.jar之前的都可以正常启动。没有遇到这个问题
