### ISSUE TITLE
玩家在地狱/末地下线，服务器重启后，玩家再次进入卡入地底窒息和虚空

### ISSUE THREAD

**Issue by susuguai** [MohistMC/Banner#269]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-662

### Java 版本 | 操作系统

系统Windwos10，Java：Zulu21.34+19-CA (build 21.0.3+9-LTS)

### 相关 Mod/插件 的名称及版本

```raw
模组[banner、fabric-api]
插件[BetterRTP、EssentialsX]
```

### 错误描述

我也遇到同样的问题，我使用的目前最新的banner-1.20.1-601-server.jar
玩家在 地狱/末地 退出游戏，重启服务器后，玩家再次进入，就会卡入地底窒息甚至虚空。
使用随机传送(例如BetterRTP、Essentials)，会卡入方块窒息。
希望得到修复。

### 复现步骤

1、安装Minecraft1.20.1Fabric最新版本，放入mod：banner、fabric-api、插件：BetterRTP、EssentialsX
2、玩家进入服务器进入地狱/末地，然后退出游戏，服务器保存并重启。
3、玩家再次进入服务器，在地狱/末地 卡入地下方块窒息死亡或者掉入虚空。
4、另外的问题：使用EssentialsX插件的随机传送或者BetterRTP传送，会卡如方块窒息。

### 报错信息

[latest.log](https://github.com/user-attachments/files/16016043/latest.log)

**Comment by wdog5734** [comment]
Fixed

**Comment by susuguai** [comment]
> 固定

### 问题依旧存在
今天刚试了试新版本banner-1.20.1-603-server，**问题依旧存在**，我翻了翻往期的问题，好像大部分的服主都遇到了该问题。
我看了那些反馈过的问题，**我认为，这个和区块加载、网络有关系。**

1. 1、**本地** 部署服务端，再用 **本地** 客户端进服127.0.0.1，似乎不会出现这个问题。

1. 2、但是，把服务端部署在 **远程服务器**，再用客户端进服，就会出现这个问题，其实 **人物的坐标(x,z)是对的，y坐标轴不对**，要么在地下的矿洞，要么卡在地下方块里。

1. 3、**我觉得前面有些玩家说的很对，似乎人物出现的太快，以至于区块没有加载完全，导致玩家y轴下降。**

1. 4、我后来通过插件AuthMe，稍微解决我目前的处境，在玩家进入服务器后还没有通过密码验证前将其传送到固定坐标，登录验证后再传回上次离线的位置，稍微解决问题。**(但是在固定坐标时，依旧是在地下，多亏AuthMe未登录时是无敌以至于玩家没有窒息)**

1. 5、通过别的插件来解决这个问题，并不是明智之举，治标不治本。

**希望能够想出正确的方案处理这个问题**，这个**问题反馈的频率很高**，但是问题没有很好的解决。
这个问题解决起来似乎挺困难，因为我在控制台并没有发现任何报错，真的是辛苦你们了，希望能够早日发现核心问题。
