### ISSUE TITLE
1.20.1 Prom II Zenith Server wont start

### ISSUE THREAD

**Issue by funnycubeguy** [MohistMC/Banner#271]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

603

### OS & Java versions

Debian 12 Java 17 Pterodactyl

### Plugins and Mods

```raw
https://www.curseforge.com/minecraft/mc-mods/zenith
https://legacy.curseforge.com/minecraft/mc-mods/zenith-attributes

With the https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg modpack
```

### Description

Server wont start

### Logs

https://pastes.dev/mSQ1qSuFQL

### Server pack link (Optional)

https://www.curseforge.com/minecraft/modpacks/prominence-2-rpg

**Comment by windy664** [comment]
与https://github.com/MohistMC/Banner/issues/245 相同

![f5be6163d121c181517dd705c7bca1c8](https://github.com/MohistMC/Banner/assets/81475218/7293de86-44e2-43ab-8638-ef7c2cc484e8)
