### ISSUE TITLE
 我无法运行LuckPerms，无论Bukkit还是Fabric。

### ISSUE THREAD

**Issue by Azusa-mikan** [MohistMC/Banner#272]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-671 #608

### Java 版本 | 操作系统

系统：Debian 11 x86_64,Zulu22.30+13-CA (build 22.0.1+8, mixed mode, sharing)

### 相关 Mod/插件 的名称及版本

```raw
LuckPerms-Fabric-5.4.137
或
LuckPerms-Bukkit-5.4.137
```

### 错误描述

LuckPerms是一个权限管理插件/MOD，支持bukkit，forge，fabric以及其它服务端
尝试启用时没法注入Mixin，我不懂，麻烦你们看看

### 复现步骤

1.安装LuckPerms
2.启动服务器

### 报错信息

[latest.log](https://github.com/user-attachments/files/16127073/latest.log) Fabric版本
[2024-07-08-3.log](https://github.com/user-attachments/files/16127077/2024-07-08-3.log) bukkit版本

### 复现用压缩包下载链接(可选)

https://azusa-mikan.frp.wo25.net:32000/d/%E9%95%BF%E6%9C%9F%E4%BF%9D%E5%AD%98%E7%9A%84%E6%96%87%E4%BB%B6/1.20.1banner.zip

**Comment by Mgazul** [comment]
yesstevemodel mod cannot be used in server

**Comment by HowardZHY** [comment]
> yesstevemodel mod cannot be used in server

It can be used in servers, and players without it can even connect to server with it installed

**Comment by windy664** [comment]
经我测试，ysm和占位符插件不兼容。
