### ISSUE TITLE
Fast Async World Edit fails durring world manipulation

### ISSUE THREAD

**Issue by Sandr-aa** [MohistMC/Banner#278]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

671

### OS & Java versions

OS: Arch Linux x86_64, Java: openjdk 21.0.4 2024-07-16

### Plugins and Mods

```raw
Plugins (1): FastAsyncWorldEdit (WorldEdit)
Mods: Fabric Loader, OpenJDK, javax.inject, jline, MixinExtras, mapping-io, adventure-api, adventure-key, adventure-platform-api, adventure-text-logger-slf4j, adventure-text-minimessage, adventure-text-serializer-ansi, adventure-text-serializer-gson, adventure-text-serializer-json, adventure-text-serializer-legacy, adventure-text-serializer-plain, examination-api, examination-string, bungeecord-chat, SpecialSource, jopt-simple, log4j-iostreams, checker-qual, jansi, sqlite-jdbc, snakeyaml
```

### Description

Any type of world manipulation with fast async worldedit seems to fail.

### Step to reproduce

(Install Banner and FastAsyncWorldEdit from https://ci.athion.net/job/FastAsyncWorldEdit/ manually or use the mcman config)
### Fill:
1. get an wand (wooden axe) and select an area with left+right click
2. replace the blocks: `//set stone`
### Brush: 
1. get an tool (e.g wooden axe), hold it and execute `//brush set cuboid 5 stone` 
2. right-click an area
### Set biome:
1. get an wand (wooden axe) and select an bigger area with left+right click
2. execute `//setbiome meadow`

### Logs

[latest.log](https://github.com/user-attachments/files/16319880/latest.log)

### Server pack link (Optional)

https://gist.github.com/Sandr-aa/ee25a4e6245f7eadf13f7659586320e1

**Comment by Mgazul** [comment]
Fixed
