### ISSUE TITLE
Mixin apply for mod betterend failed betterend.mixins.common.json:LivingEntityMixin from mod betterend -> net.minecraft.class_1309 (1.20.1) -better-end-4.0.11

### ISSUE THREAD

**Issue by TeQTabanca** [MohistMC/Banner#285]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.20.1-686, Java 66.0

### OS & Java versions

java version "22.0.1" 2024-04-16 | Java(TM) SE Runtime Environment (build 22.0.1+8-16)

### Plugins and Mods

```raw
I cannot post the plugin and mod list because the server crashed after giving the error.
```

### Step to reproduce

1. Install the From better-end-4.0.11 mod.
2. Start the server.

**Comment by ERroooooR** [comment]
可以复现

**Comment by ERroooooR** [comment]
https://mclo.gs/e871Qgx

**Comment by ERroooooR** [comment]
经测试，应该是这个提交引起的  https://github.com/MohistMC/Banner/commit/2d7c0922e6a785d5dcf21436d7982dc8cb800b79

**Comment by ERroooooR** [comment]
fixed
