### ISSUE TITLE
[1.20.1] 加入机械动力，启动完成后服务器崩溃

### ISSUE THREAD

**Issue by Star-Jirachi** [MohistMC/Banner#288]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-625-server

### Java 版本 | 操作系统

win10 zulu17.46.19-ca-jdk17.0.9-win_x64

### 相关 Mod/插件 的名称及版本

```raw
mod:
fabric-api-0.92.2+1.20.1
banner-1.20.1-625-server
create-fabric-0.5.1-f-build.1417+mc1.20.1
```

### 错误描述

启动服务器，服务器启动成功后，会在10秒内崩溃，即使没人加入。

### 复现步骤

1.启动服务器
2.启动完成后服务器崩溃

### 报错信息

日志及崩溃报告：
[latest.log](https://github.com/user-attachments/files/16407402/latest.log)
[crash-2024-07-29_12.22.34-server.txt](https://github.com/user-attachments/files/16407404/crash-2024-07-29_12.22.34-server.txt)

**Comment by windy664** [comment]
Your banner is too late，plz update it.

**Comment by Star-Jirachi** [comment]
> Your banner is too late，plz update it.

在我提交时banner就是最新的，只不过banner下载地址显示的版本是625.
日志输出界面显示的是
This server is running Banner version 1.20.1-688
