### ISSUE TITLE
dev-bug: Invalid Player Data (broken Food Data Mixin)

### ISSUE THREAD

**Issue by Merith-TK** [MohistMC/Banner#29]
I am opening these bug reports for issues as I find them, I will me working on an format for them as I come across them, open for suggestions as this bug report is the format I am thinking of
```md
# dev-bug: <bug name in human (not programmer) language>

<the error line from the log>
<the log file + Line Number where error occured> 

<brief description of error>
```

`java.lang.RuntimeException: Mixin transformation of net.minecraft.world.food.FoodData failed`
[specific error](https://haste.mohistmc.com/amonoxekif.properties)

Upon Player connect, it appears that data relating to "Hunger" (inferred from `FoodData`) is not fully implemented and functional yet, causing an `invalid player data` error

**Comment by 1798643961** [comment]
Keep wating unless PlayerList.patch has been mixined

**Comment by Merith-TK** [comment]
Appears to be fixed? Waiting on PlayerList to confirm
