### ISSUE TITLE
模组无法管理插件提供的权限

### ISSUE THREAD

**Issue by gujiu001** [MohistMC/Banner#297]
### 请确认您已完成以下几件事

- [x] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-697

### Java 版本 | 操作系统

系统：Linux   Java：17

### 相关 Mod/插件 的名称及版本

```raw
Plugins (8): CMILib, ViaVersion, NBTAPI, Essentials, EssentialsSpawn, EssentialsChat, QuickShop-Hikari, Residence
Mods: adventure-platform-fabric, Architectury, Banner Mod, mixin-tools, json-simple, dynamicenum, i18n, mysql-connector-j, commons-codec, commons-lang, Fabric API, Fabric Convention Tags, fabric-permissions-api, Fabric Loader, FTB Library, FTB Ultimine, OpenJDK, javax.inject, jline, LuckPerms, MixinExtras, mapping-io, adventure-api, adventure-key, adventure-platform-api, adventure-text-logger-slf4j, adventure-text-minimessage, adventure-text-serializer-ansi, adventure-text-serializer-gson, adventure-text-serializer-json, adventure-text-serializer-legacy, adventure-text-serializer-plain, examination-api, examination-string, bungeecord-chat, SpecialSource, jopt-simple, log4j-iostreams, checker-qual, jansi, sqlite-jdbc, snakeyaml
```

### 错误描述

插件EssentialX提供了许多权限节点与命令
LuckPerms可以用来管理权限节点
在使用「模组」（LuckPerms）时，该「模组」（LuckPerms）无法管理「插件(通过Banner)」（EssentialX）提供的权限节点

### 复现步骤

1.安装LuckPerms的Fabric版
2.安装EssentialX （通过Banner）
3.启动服务器
4.尝试使用LuckPerms给任意玩家增加来自EssentialX的权限节点（成功）
5.玩家尝试使用该权限节点提供的指令（你没有使用该命令的权限。）

**Comment by gujiu001** [comment]
不确定插件能否管理模组（没试过）

**Comment by windy664** [comment]
plugin装个lp，mods也装个lp注意两个版本不要一样

plugin的lp指令则用
/luckperms:lp
mod的lp指令用
/lp 

然后两个lp连接同一个Mysql数据库解决。
