### ISSUE TITLE
fakeplayer插件无法运行

### ISSUE THREAD

**Issue by Superxp666** [MohistMC/Banner#301]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

1.20.1-707

### Java 版本 | 操作系统

windows server 2022 java-17.0.12

### 相关 Mod/插件 的名称及版本

```raw
CoreProtect, CommandAPI, LuckPerms, PlaceholderAPI, ProtocolLib, CMILib, fakeplayer, TAB, MaintenanceMOTD, Ip2region, TabTPS, CMI
```

### 错误描述

fakeplayer 无法运行，命令用不了，配置文件能够加载出来

### 报错信息

[latest.log](https://github.com/user-attachments/files/16701170/latest.log)

**Comment by jdnjk** [comment]
为何不用carpet？

**Comment by Superxp666** [comment]
> 为何不用地毯？
playerlist 总显示anonymous user 想试试插件怎么显示

**Comment by Mgazul** [comment]
fakeplayer仅paper可用
