### ISSUE TITLE
Banner 1.21.1-55 纯净服务端无法正常启动

### ISSUE THREAD

**Issue by LittleKing2004** [MohistMC/Banner#304]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner 1.21.1-55

### Java 版本 | 操作系统

zulu21.30.15-ca-jdk21.0.1-win_x64

### 相关 Mod/插件 的名称及版本

```raw
无添加任何模组 插件
```

### 错误描述

如标题

### 复现步骤

下载banner-launcher-1.21.1-55.jar

使用bat启动
参数：
chcp 65001
@ECHO OFF
"D:\Java\JDK\zulu21.30.15-ca-jdk21.0.1-win_x64\bin\java.exe" -Xms2G -Xmx2G -jar  banner-launcher-1.21.1-55.jar nogui
pause

然后卡在了
![PixPin_2024-09-04_00-03-00](https://github.com/user-attachments/assets/a8d0c78e-bbe0-4010-8565-5a02e2dd35ce)

我在 https://www.minecraft.net/zh-hans/download/server 手动下载了最新的官方服务器核心，日期2024.9.4
丢到了libraries\net\minecraft\server\1.21.1目录下。

再次启动Banner之后，检测到了server-1.21.1.继续加载一些东西
之后又卡住了。

### 报错信息

报错日志 
https://mclo.gs/oEnUMAJ
或者
https://paste.ubuntu.com/p/c4pRPjYJ3H/

**Comment by Mgazul** [comment]
第二个问题已修复
