### ISSUE TITLE
Banner 1.21.1 can't join to the server

### ISSUE THREAD

**Issue by esoty6** [MohistMC/Banner#305]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

Banner version 1.21.1-75

### OS & Java versions

Win 11, Java 21

### Plugins and Mods

```raw
None
```

### Description

Server starts normally, but I can't join (freezes on Encrypting step and fails after). On server join it throws exception. I've tried it with online set to true and false and got different errors (both logs below).

### Step to reproduce

1. Install banner
2. Run server
3. Join to the server
4. Can't join

### Logs

[latest.log - online true](https://github.com/user-attachments/files/16891763/latest.log)

[latest.log - online false](https://github.com/user-attachments/files/16892259/latest.log)

**Comment by Stark1997y** [comment]
+
