### ISSUE TITLE
dev-bug: Server acts like world is under SpawnProtection even when opped

### ISSUE THREAD

**Issue by Merith-TK** [MohistMC/Banner#32]
### Commit ID

MohistMC/1.19.4/eace9ab407fb9266bd363e1d311c66177c23f209

### Log with Error

[latest.log](https://haste.mohistmc.com/fisepamozo.sql)

### Description of Error

attempting to place or break blocks (vanilla or modded) the server responds by not doing anything, acting as if spawn protection is enabled with an ∞ radius

**Comment by 1798643961** [comment]
Hmmm,could you please use pastebin instead of hastebin?

**Comment by Merith-TK** [comment]
*dont blame me for that, thats mohists own hastebin*
https://pastebin.com/YDmjAE22

**Comment by wdog5** [comment]
It has been fixed recently
