### ISSUE TITLE
[1.21.1] Uncaught exception in thread "main"

### ISSUE THREAD

**Issue by ToshiNamura** [MohistMC/Banner#330]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

banner-1.21.1-133-server

### OS & Java versions

OS: Windows 10, Java: 21.0.4 2024-07-16 LTS

### Plugins and Mods

```raw
Mods in main/INFO:
banner-launcher 1.21.1-133
fabricloader 0.16.7
fabric-api 0.106.0+1.21.1
java 21
minecraft 1.21.1

Plugins are not installed.
```

### Description

When the server starts, it returns an error:
![Screenshot](https://github.com/user-attachments/assets/751de006-e49f-461e-b9d8-4e7b66daf7c4)

### Step to reproduce

1. Install Fabric Loader.
2. Install Minecraft Server Jar File 1.21.1.
3. Install fabric-server-launch.jar
4. Install fabric-api-0.106.0+1.21.1.jar
5. Install latest MohistMC Banner.
6. launching in bat script:
```bat
chcp 65001
java -Xms1024M -jar fabric-server-launch.jar --nogui --universe worlds
```

### Logs

[latest.log](https://github.com/user-attachments/files/17444683/latest.log)

**Comment by wdog5734** [comment]
Launch with command java -jar banner-launcher-version.jar
