### ISSUE TITLE
Unable to even start 1.21.1

### ISSUE THREAD

**Issue by L0rdLogan** [MohistMC/Banner#338]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

1.21.1

### OS & Java versions

Debian 12 - Java 21

### Plugins and Mods

```raw
Mods: 

banner-1.21.1-149-server.jar
fabric-api-0.102.1+1.21.1.jar

Plugins: None
```

### Description

Cannot get the server to launch at all for some reason

### Step to reproduce

1. Install Banner on a working Fabric server

### Logs

https://mclo.gs/7Iw8QTE

**Comment by EchoNews615** [comment]
The my start only... but only starting session... the banner  1.20.1 is functional, but the mods not working and the arclight no fuctional in 1.21.1
