### ISSUE TITLE
PalettedContainer.class -> java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by Quenteez** [MohistMC/Banner#42]
### Commit ID

MohistMC/1.19.4

### Log with Error

https://haste.mohistmc.com/duladedumi.sql

### Description of Error

`java.lang.NoClassDefFoundError: net/minecraft/class_2841$d` when I try to generate an island. As far as I understand, `class_2841$d` is the NMS class `PalettedContainer<>`. I was thinking of adding it myself, but I didn't see the implementation of NMS classes in **Banner** at all (except for patches).
You can see where the error is caused when executing the code by the plugin: [here](https://github.com/BG-Software-LLC/SuperiorSkyblock2/blob/master/NMS/v1194/src/main/java/com/bgsoftware/superiorskyblock/nms/v1194/world/WorldEditSessionImpl.java#L264).

**Comment by wdog5** [comment]
It is on the spigot2srg

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/5e54d6b6-cd43-42fc-9cbc-20536eedd398)

**Comment by wdog5** [comment]
we use remapper to remap plugin nms name to intermediatly names,maybe the nms remapper has some errors

**Comment by Quenteez** [comment]
Yes, I saw. It seems that when building this class is not applied or something like that. Or, as you said, the remapper contains errors
