### ISSUE TITLE
MixinDedicatedServer.class -> java.lang.ClassCastException

### ISSUE THREAD

**Issue by Quenteez** [MohistMC/Banner#43]
### Commit ID

MohistMC/1.19.4

### Log with Error

https://haste.mohistmc.com/usahufekid.yaml

### Description of Error

The error occurs after entering the `/stop` command (it is also possible in other cases, I do not know this). At the same time, after restarting the server, the changes that occurred on the server are rolled back (the players return to the previous coordinates, the terrain is regenerated, the inventory returns to its previous state). Perhaps these 2 things are not related in any way, but I decided to mention it here.
By the error itself, it can be understood that some private class cannot be cast to class `net.minecraft.class_3176`, i.e. `DedicatedServer` (based on Mojang mappings).
Link to MixinDedicatedServer [here](https://github.com/MohistMC/Banner/blob/1.19.4/src/main/java/com/mohistmc/banner/mixin/core/server/dedicated/MixinDedicatedServer.java).

P. S. I saw that some edits were made after I finished writing this topic ([commit](https://github.com/MohistMC/Banner/commit/771575fae2e6ccc59cf7f0f61e78496c7cbdd1f5)), so if this is no longer relevant, then I apologize

**Comment by Quenteez** [comment]
It also turned out that the error occurs **only when entering a command from the console** (not always:  randomly, or on certain commands).
I will also add that the console works in a strange way, namely, you have to press the same key 2 times so that the first character of the command is printed (each time you enter a new command). This also includes the absence of tabs for nicknames, commands and their arguments inside the console.

**Comment by Merith-TK** [comment]
Was having this issue when running command from ingame, please re-verify

**Comment by wdog5** [comment]
Fixed by the commit about player data and player online number
