### ISSUE TITLE
Collision bug with entity

### ISSUE THREAD

**Issue by Teyk0o** [MohistMC/Banner#45]
### Commit ID

a326470

### Log with Error

https://mclo.gs/wr50Yu3

### Description of Error

A bug appear when you collide with a mob or any entity, he block you totally and sometimes he doesn't move.
When you tried to jump on entity you are stuck and freeze on this entity.

**Comment by muriplz** [comment]
happens on f06933a0365940c73733f5d9c782e803e9febabe too. This happens only Player - Entity (any kind of entity). This does **not** happen between Entities if neither are players

**Comment by muriplz** [comment]
Digging deeper, I remember Mohist had this exact same issue. Here it is https://github.com/MohistMC/Mohist/issues/1061
