### ISSUE TITLE
Give command didn't work properly

### ISSUE THREAD

**Issue by Teyk0o** [MohistMC/Banner#46]
### Commit ID

a326470

### Log with Error

https://mclo.gs/ZnyMXIf

### Description of Error

When i try to give myself something with the /give <username> <item> command the server always return me "Unknow Item".

![image](https://github.com/MohistMC/Banner/assets/61880621/389266f1-0c16-44e7-be58-6935b50d145f)

**Comment by Teyk0o** [comment]
EDIT : All commands who need block name (/fill, /give, ex...)

**Comment by wdog5** [comment]
Please use minecraft:give at now to resolve this problem as an alternatvie choice
