### ISSUE TITLE
Entity flying

### ISSUE THREAD

**Issue by Teyk0o** [MohistMC/Banner#47]
### Commit ID

a326470

### Log with Error

https://mclo.gs/agfARJ8

### Description of Error

Sometimes when the entity are generated she fliying and keep flying around 30 seconds (with moving).

![image](https://github.com/MohistMC/Banner/assets/61880621/4ff2ae6c-4d61-443b-ba4f-3c452ba00a21)

**Comment by wdog5** [comment]
Check you RAM is able to running server
