### ISSUE TITLE
Unable to go to End though portal

### ISSUE THREAD

**Issue by Teyk0o** [MohistMC/Banner#48]
### Commit ID

a326470

### Log with Error

https://mclo.gs/BHzxuYY

### Description of Error

Nether is OK but im unable to go to end.
In world folder the end is generated but i can't go to it.

![image](https://github.com/MohistMC/Banner/assets/61880621/6ae7bb19-77c3-4f97-be39-2b2e9087c726)

**Comment by thaumstrial** [comment]
@Teyk0o Thank you for your feedback. The end portal should work correctly in the latest version of 1.19.4.
