### ISSUE TITLE
Multiverse-Core does not see some worlds

### ISSUE THREAD

**Issue by Quenteez** [MohistMC/Banner#51]
### Commit ID

MohistMC/1.19.4

### Log with Error

https://haste.mohistmc.com/obunidixab.sql

### Description of Error

Multiverse-Core recognizes only 2 worlds (`world` and `SuperiorWorld` - the world that creates the plugin `SuperiorSkyblock2`). These 2 worlds are located in the root folder of the server (in the same place as fabric-server). While there are still worlds: `DIM1` and `DIM-1`, but in the `world` folder. These 2 worlds correspond to `world_nether` and `world_the_end`, which should actually lie in the root folder of the server, as it is arranged on the basis of Spigot (however, this is not the case).

**Comment by wdog5** [comment]
MV is incompatible after mc version 1.13 when use hybrid server

**Comment by wdog5** [comment]
it is better to ask the plugin's author to add the hybrid server compat, because it is difficult to compat with MV by hybrid server itself since the bukkit format is different with orginal minecraft format

**Comment by Quenteez** [comment]
Hmm, I could try to build a modified MV in my spare time using the available methods within the Banner project. This would be the simplest solution, since the authors of plugins categorically do not welcome hybrid server builds (in particular, EssentialsX strongly focuses on this)

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/e0f684a3-d88a-4d68-a803-b686d6791faf)

**Comment by wdog5** [comment]
https://github.com/MohistMC/Banner/commit/78abcc599566512e6daf789979fcee0c2a5f69e9

**Comment by wdog5** [comment]
Use symlink world that can be compat with mv
