### ISSUE TITLE
net.minecraft.class_2519.f_() -> java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Quenteez** [MohistMC/Banner#56]
### Commit ID

MohistMC/1.19.4

### Log with Error

https://haste.mohistmc.com/rurinosofo.md

### Description of Error

This error occurs when the `SuperiorSkyblock2` plugin is enabled. 
By **Mojang** mappings it's `StringTag.getAsString()`, by **Yarn** mappings it's `NbtElement.asString()`.
Then the server crashes.

**Comment by wdog5** [comment]
Check it if it paper only plugin,because paper added new method
