### ISSUE TITLE
[1.20.1-rc1] Cancelling bukkit's EntityDamageEvent on a player

### ISSUE THREAD

**Issue by muriplz** [MohistMC/Banner#57]
### Commit ID

<MohistMC/Banner/f06933a>

### Log with Error

No error

### Description of Error

https://github.com/MohistMC/Banner/assets/46825658/bcdf2a6a-aaf0-4cac-a5b2-9151a7b13d78

When cancelling EntityDamageEvent The sound and camera movement from the client still happen
```
@EventHandler(priority = EventPriority.HIGHEST)
public void preventFirstFall(EntityDamageEvent event) {
      if(condition) {
            event.setCancelled(true);
      }
}

**Comment by wdog5** [comment]
Fixed by Spigot

**Comment by muriplz** [comment]
this one is still happening, although it's not a big deal
