### ISSUE TITLE
从单人移入存档 所有方块消失

### ISSUE THREAD

**Issue by DreamSoulFire** [MohistMC/Banner#65]
### Commit ID

jenkins里的最新版本

### Log with Error

无报错

### Description of Error

从单人移入存档 所有方块消失

**Comment by DreamSoulFire** [comment]
问题未得到解决 悲
不过辛苦大佬了

**Comment by wdog5** [comment]
存档不支持非英文名字...

**Comment by DreamSoulFire** [comment]
但是存档名就是英文啊

**Comment by wdog5** [comment]
Fixed
