### ISSUE TITLE
后台使用say指令后报错task failed，进服后崩服

### ISSUE THREAD

**Issue by ArisCM** [MohistMC/Banner#69]
### Commit ID

核心版本：fabric-server-mc.1.20.1-loader.0.14.21-launcher.0.11.2
banner版本：banner-1.20.1-97.jar
api版本：fabric-api-0.84.0+1.20.1.jar

### Log with Error

log日志：https://haste.mohistmc.com/ohewuxuqik.makefile
crash-reports日志：https://haste.mohistmc.com/akawupaqel.kotlin

### Description of Error

后台使用say指令后报错task failed，进服后崩服

![1](https://github.com/MohistMC/Banner/assets/85684519/db6d99ff-fa79-4348-850a-07d5162e46bf)
![2](https://github.com/MohistMC/Banner/assets/85684519/c4110e53-4f97-456b-97b5-17221ea82099)
![3](https://github.com/MohistMC/Banner/assets/85684519/eab70073-9630-4c69-ab29-ad854e781f4c)

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/c31cce35-3424-413c-9787-e122689424a2)

**Comment by wdog5** [comment]
因为banner实际上是个mod，所以无法加载到本来应该作为服务端核心的bukkit，目前几乎无解
