### ISSUE TITLE
bug with portals

### ISSUE THREAD

**Issue by 1-nkl** [MohistMC/Banner#70]
### Commit ID

https://github.com/MohistMC/Banner/actions/runs/5341442827

### Log with Error

no errors

### Description of Error

https://youtu.be/UQmoKuOUjZQ

**Comment by wdog5** [comment]
please use pastebin,hmmmm

**Comment by wdog5** [comment]
I cannot access the youtube

**Comment by NerdTo** [comment]
wdog

**Comment by NerdTo** [comment]
Why can't you watch this video from Discord?

**Comment by NerdTo** [comment]
https://cdn.discordapp.com/attachments/1111669700498300989/1121370075140718602/20230622-0919-43.4516161.mp4

**Comment by NerdTo** [comment]
> https://cdn.discordapp.com/attachments/1111669700498300989/1121370075140718602/20230622-0919-43.4516161.mp4

Download it from this link

**Comment by wdog5** [comment]
ok thanks
