### ISSUE TITLE
关于重新加入服务器导致Y轴减少问题

### ISSUE THREAD

**Issue by Zao-chen** [MohistMC/Banner#73]
在每次进入游戏时会导致Y轴减少。
我发现这应该是一个与网络有关的问题。
如果您的服务器和客户端在同一台计算机上，则不会出现此问题。
如果没有，那么就会出现这种情况。
我认为玩家在加载世界之前就进入了世界，然后没有方块进行自由落体
因为我发现如果玩家在飞行的状态下冲进，Y值不会减少。
版本：[114](https://github.com/MohistMC/Banner/actions/runs/5456008525)

_Originally posted by @Zao-chen in https://github.com/MohistMC/Banner/issues/60#issuecomment-1621287465_

**Comment by Zao-chen** [comment]
依然未解决，发现Y下降的程度和地图加载时长有关。
就像是在地图没加载完的时候玩家就出生看一样，
使用最新版banner-1.20.1-392依然可以复现。
## 复现方法：
1. 服务器和客户端非本地链接
2. 服务器和客户端的网络非最佳状态
3. 重新加入世界


请求重新打开issue。

https://github.com/MohistMC/Banner/assets/77674075/dc7f3290-885d-4ec0-b72d-09ea11bf2c80

**Comment by LovelyRua** [comment]
this issue has not been fixed in version 722
