### ISSUE TITLE
在Windows上运行没有主清单属性

### ISSUE THREAD

**Issue by 5ur3z** [MohistMC/Banner#80]
### Commit ID

banner-1.20.1-147

### Log with Error

none

### Description of Error

banner-1.20.1-147.jar中没有主清单属性

bat脚本：
:start
"C:\Program Files\Zulu\zulu-18\bin\java.exe" -Xms8192M -Xmx8192M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -jar banner-1.20.1-147.jar

echo Server restarting...
echo Press CTRL + C to stop.
goto :start

**Comment by wdog5** [comment]
banner是个mod，请安装fabric服务端后，将banner放入mods文件夹
