### ISSUE TITLE
Some command doesn't work

### ISSUE THREAD

**Issue by magojohnji** [MohistMC/Banner#81]
### Commit ID

banner-1.20.1-160.jar

### Log with Error

None

### Description of Error

Entering the /op command in the console does not work (even /help does not work)
![Uploading 8da3911ca4eef6fc2a71a8d7dc452e34.png…]()

**Comment by magojohnji** [comment]
![8da3911ca4eef6fc2a71a8d7dc452e34](https://github.com/MohistMC/Banner/assets/69509738/86ddd4c0-cfe0-420d-a5c6-fcbd360416d2)

**Comment by wdog5** [comment]
do not need to print /

**Comment by wdog5** [comment]
just print help/op etc...

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/cf1374ed-bda1-4639-b52e-def85bb3d98f)

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/189cda11-2275-43d2-af2a-bf4546d8385a)

**Comment by magojohnji** [comment]
Thank you very much. Banner is nice.
