### ISSUE TITLE
下界&末地传送门无法正确传送

### ISSUE THREAD

**Issue by Fengkiy** [MohistMC/Banner#87]
### 请确认您已完成以下几件事

- [X] 正在使用最新的 Banner
- [X] 已为所有插件及模组安装依赖
- [X] 已为所有插件及模组更新至最新版
- [X] 不可在 Spigot 复现
- [X] 不可在 Fabric 复现

### Banner 版本

banner-1.20.1-238

### Java 版本 | 操作系统

openjdk version "17.0.7" 2023-04-18 LTS ; Windows 10 Pro 19045.3208

### 相关 Mod/插件 的名称及版本

```raw
仅安装 banner 和 fabric api 模组，无插件
```

### 错误描述

搭建下界传送门后，无法传送到下界；搭建末地传送门后，末地与主世界相重叠

### 复现步骤

1. 仅安装 banner 和 fabric api 模组后，启动服务器
2. 搭建下界传送门后，无法传送到下界；搭建末地传送门后，末地与主世界相重叠

生成的世界文件夹可以像 paper 一样，拆分为 world、world_nether、world_the_end，而不是一个综合的 world 吗？

### 报错信息

以下是上传的logs
https://fengki-my.sharepoint.com/:f:/g/personal/feng_fengki_onmicrosoft_com/Epki-OzNJ8ZFlxYNDzI1dl4BFsK9t94ihFv3bICQewPAQw?e=z6sRug

[logs.zip](https://github.com/MohistMC/Banner/files/12175240/logs.zip)

**Comment by wdog5** [comment]
实际上还是综合的world,只是创建了symlink
