### ISSUE TITLE
Trees won't grow with bonemeal

### ISSUE THREAD

**Issue by Geo3gamer** [MohistMC/Banner#88]
### I have confirmed that ...

- [x] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [x] unable to reproduce in Fabric

### Banner version

253

### OS & Java versions

OS: Windows 10 22H2 19045.3208 Java: openjdk version "17.0.5" 2022-10-18

### Plugins and Mods

```raw
Plugins (1): Slimefun

Name : Slimefun
Version : DEV - 1087 (git dc22e665)

Mods: Banner Mod, MixinExtras, mixin-tools, i18n, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, mapping-io, terminalconsoleappender, log4j-iostreams, jline-terminal, jline-terminal-jansi, snakeyaml
```

### Description

Tree saplings don't grow with bonemeal, but grow when randomTickSpeed at 1000.

### Logs

[latest (2).log](https://github.com/MohistMC/Banner/files/12185552/latest.2.log)

**Comment by wdog5** [comment]
Fixed at https://github.com/MohistMC/Banner/commit/d48a7efe510bde5dcc2d8efb792c4eb2cf43d0ed
