### ISSUE TITLE
Translations in join messages are broken

### ISSUE THREAD

**Issue by Geo3gamer** [MohistMC/Banner#92]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

260

### OS & Java versions

OS: Windows 10 22H2 19045.3208 Java: openjdk version "17.0.5" 2022-10-18

### Plugins and Mods

```raw
Plugins (1): Slimefun

Name : Slimefun
Version : DEV - 1087 (git dc22e665)

Mods: Banner Mod, MixinExtras, mixin-tools, i18n, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, mapping-io, terminalconsoleappender, log4j-iostreams, jline-terminal, jline-terminal-jansi, snakeyaml
```

### Description

![picture](https://github.com/MohistMC/Banner/assets/47525358/670c784e-4ef6-4b8b-a52f-865108195740)

**Comment by Geo3gamer** [comment]
`Player joined the game` text should be translated to `Player присоединился к игре` by default in Russian localization of game. You can check it in other languages.

**Comment by wdog5** [comment]
Are you install any translator mod in client?

**Comment by wdog5** [comment]
the join message is handled by bukkit,if you want you can try the bukkit side translator plugins

**Comment by wdog5** [comment]
![image](https://github.com/MohistMC/Banner/assets/40519136/b3c908f3-b0d5-4cb8-8c99-dc9483452d3d)

because bukkit changed it
