### ISSUE TITLE
TAB plugin not working

### ISSUE THREAD

**Issue by ElMiloPy** [MohistMC/Banner#93]
### I have confirmed that ...

- [X] Banner is up to date
- [X] all dependencies are installed
- [X] all plugins and mods are up to date
- [X] unable to reproduce in Spigot
- [X] unable to reproduce in Fabric

### Banner version

270

### OS & Java versions

OS: Windows 11 x64, Java: openjdk 17.0.7 2023-04-18

### Plugins and Mods

```raw
Plugins (1): TAB

Mods: Banner Mod, MixinExtras, mixin-tools, i18n, Fabric API, Fabric Convention Tags, Fabric Loader, OpenJDK, mapping-io, terminalconsoleappender, log4j-iostreams, jline-terminal, jline-terminal-jansi, snakeyaml
```

### Description

TAB aims to be a superior all-in-one minecraft plugin for displaying information that outperforms all similar plugins in terms of features, performance and compatibility.

Link: https://github.com/NEZNAMY/TAB

It should not give this message and be disabled, unfortunately I don't know how to make it show the error that the plugin is having.

The message:
[TAB] Enabling TAB v4.0.3
[TAB] A compatibility issue with your server was found. Unless you are running some really weird server software, this is a bug.
[TAB] Disabling TAB v4.0.3

### Step to reproduce

1. Install banner and fabric-api.
2. Put tab.jar in the plugins folder.
3. Run

### Logs

[latest.log](https://github.com/MohistMC/Banner/files/12207865/latest.log)

**Comment by ElMiloPy** [comment]
Banner version: banner-1.20.1-270.jar

**Comment by wdog5** [comment]
Tab has fabric version,it is not need to use bukkit version.
https://github.com/NEZNAMY/TAB/tree/master/fabric
